$primary             = c0c1ff
$onPrimary           = 282a60
$primaryContainer    = 3f4178
$onPrimaryContainer  = e1e0ff
$secondary           = c6c4dd
$onSecondary         = 2e2f42
$secondaryContainer  = 454559
$onSecondaryContainer = e2e0f9
$background          = 131318
$onBackground        = e4e1e9
$surface             = 131318
$onSurface           = e4e1e9
$surfaceVariant      = 46464f
$onSurfaceVariant    = c7c5d0
$outline             = 918f9a
$outlineVariant      = 46464f
$surfaceContainer    = 1f1f25
$surfaceContainerHigh = 2a292f
$surfaceContainerLow  = 1b1b21
$error               = ffb4ab
$onError             = 690005

# Alias con opacidad
$primarye6           = c0c1ffe6
$primaryd4           = c0c1ffd4
$outlined4           = 918f9ad4
$secondaryd4         = c6c4ddd4
$surfaced4           = 131318d4
$onSurfaceVariant11  = c7c5d011
