$hypr = ~/.config/hypr
$hl   = $hypr/hyprland

# Colores dinámicos generados por Matugen
exec = cp -L --no-preserve=mode --update=none $hypr/scheme/default.conf $hypr/scheme/current.conf
source = $hypr/scheme/current.conf

# Variables generales
source = $hypr/variables.conf

# Monitor
monitor=eDP-1,1920x1080@120.00,-384x0,1.00
monitor=HDMI-A-1,1920x1080@60.00,1536x0,1.00

# Configs
source = $hl/env.conf
source = $hl/general.conf
source = $hl/input.conf
source = $hl/misc.conf
source = $hl/animations.conf
source = $hl/decoration.conf
source = $hl/group.conf
source = $hl/execs.conf
source = $hl/rules.conf
source = $hl/keybinds.conf

# NVIDIA / Optimus
explicit_sync    = 2
unscale_layers   = true

xwayland {
    force_zero_scaling = true
}
