# === Apps ===
$terminal     = kitty
$browser      = zen-browser
$editor       = nvim
$fileExplorer = yazi

# === Touchpad ===
$touchpadDisableTyping = false
$touchpadScrollFactor  = 0.3
$workspaceSwipeFingers = 4
$gestureFingers        = 3

# === Blur ===
$blurEnabled          = true
$blurSpecialWs        = true
$blurPopups           = false
$blurInputMethods     = true
$blurSize             = 1
$blurPasses           = 4
$blurXray             = false
$blurNewOptimizations = true

# === Sombras ===
$shadowEnabled     = false
$shadowRange       = 2
$shadowRenderPower = 3
$shadowColour      = rgba($surfaced4)

# === Gaps ===
$workspaceGaps      = 10
$windowGapsIn       = 5
$windowGapsOut      = 10
$singleWindowGapsOut = 10

# === Ventanas ===
$windowOpacity              = 0.92
$windowRounding             = 8
$windowBorderSize           = 2
$activeWindowBorderColour   = rgba($primarye6)
$inactiveWindowBorderColour = rgba($onSurfaceVariant11)

# === Misc ===
$volumeStep   = 5
$cursorTheme  = Bibata-Modern-Classic
$cursorSize   = 24

# === Keybinds: Workspaces ===
$kbMoveWinToWs    = Super+Alt
$kbGoToWs         = Super
$kbNextWs         = Ctrl+Super, right
$kbPrevWs         = Ctrl+Super, left
$kbToggleSpecialWs = Super, S

# === Keybinds: Ventanas ===
$kbMoveWindow          = Super, Z
$kbResizeWindow        = Super, X
$kbPinWindow           = Super, P
$kbWindowFullscreen    = Super, F
$kbWindowBorderedFullscreen = Super+Alt, F
$kbToggleWindowFloating = Super+Alt, Space
$kbCloseWindow         = Super, Q
$kbWindowGroupCycleNext = Alt, Tab
$kbWindowGroupCyclePrev = Shift+Alt, Tab
$kbToggleGroup         = Super, Comma
$kbUngroup             = Super, U

# === Keybinds: Apps ===
$kbTerminal     = Super, T
$kbBrowser      = Super, W
$kbEditor       = Super, C
$kbFileExplorer = Super, E

# === Keybinds: Misc ===
$kbLock    = Super, L
$kbSysmon  = Ctrl+Shift, Escape
