decoration {
    rounding = $windowRounding

    blur {
        enabled          = $blurEnabled
        xray             = $blurXray
        special          = $blurSpecialWs
        ignore_opacity   = false
        new_optimizations = $blurNewOptimizations
        popups           = $blurPopups
        input_methods    = $blurInputMethods
        size             = $blurSize
        passes           = $blurPasses
    }

    shadow {
        enabled      = $shadowEnabled
        range        = $shadowRange
        render_power = $shadowRenderPower
        color        = $shadowColour
    }
}
